### ISSUE TITLE
Features for FRD evaluation

### ISSUE THREAD

**Issue by kazuto1011** [vzyrianov/lidargen#4]
Thank you for sharing your work. I have a question about the FRD evaluation.
The paper suggests that:

> We choose RangeNet++, which is a encoder-decoder based network for segmentation pretrained on KITTI-360. To trade-off between quality and and preserve locality, we randomly choose 4,096 activation from the feature map of its bottleneck layer to fit the Gaussian distribution.

Meanwhile, the code seems to extract features from the *penultimate* layer pretrained on *SemanticKITTI*.
The [README](https://github.com/vzyrianov/lidargen#baselines-and-eccv22-benchmark-samples) also mentions differences of the score from the paper.
Is this the recommended and proper version? Or plan to release the KITTI-360 weights?

**Comment by vzyrianov** [comment]
Hello Kazuto, thank you for checking out our paper! 

The code contains the FRD calculation method used for the results, so it is the version that we recommend. The note in the readme is regarding the fact that to compute an FID a subset of the features are chosen (and a random mask needs to be generated).

**Comment by kazuto1011** [comment]
Thank you for the clarification!
